version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hms
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3406:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hms-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - hms-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hms-network
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  hms-network:
